name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # Change this if your default branch has a different name
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages  # This is typically the branch GitHub Pages uses
          folder: dist  # This should match your Astro build output directory